# Generated by Django 3.2 on 2021-04-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transcao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcao',
            new_name='Transacao',
        ),
    ]
